server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:arsenalwebdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate   # Usamos Flyway, no generamos el esquema automáticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration

# Configuración propia para CORS
app:
  cors:
    allowed-origins: "http://localhost:4200"
